[package]
name = "immersive-wallpapers-x11-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
image = "0.24.6"
tempfile = "3.4.0"
