name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build CLI
        working-directory: cli
        run: cargo build --verbose
      - name: Run CLI tests
        working-directory: cli
        run: cargo test --verbose
      - name: Build GUI
        working-directory: gui
        run: cargo build --verbose
      - name: Run GUI tests
        working-directory: gui
        run: cargo test --verbose
